# Generated by Django 2.1.5 on 2020-05-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_question_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_score',
            field=models.IntegerField(choices=[(1, 'Low'), (10, 'Medium'), (100, 'High')], default=1),
        ),
    ]
